version: "3.8"

services:
  postgres:
    image: postgres:15.15
    environment:
      POSTGRES_USER: cdn
      POSTGRES_PASSWORD: cdn
      POSTGRES_DB: cdn_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

  localstack:
    image: localstack/localstack:latest-amd64
    environment:
      SERVICES: sqs
      EDGE_PORT: "4566"
    ports:
      - "4566:4566"

  # TODO: Add cdn-api and cdn-worker containers when their dockerfiles are readyccd
  cdn-api:
    build: ../apps/cdn-api
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: cdn
      DB_PASSWORD: cdn
      DB_NAME: cdn_dev

      S3_ENDPOINT: http://localhost:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_BUCKET_RAW: cdn-raw
      S3_BUCKET_PROCESSED: cdn-processed
      QUEUE_URL: http://localhost:4566/000000000000/cdn-jobs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - localstack

  cdn-worker:
    build: ../apps/cdn-worker
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: cdn
      DB_PASSWORD: cdn
      DB_NAME: cdn_dev

      S3_ENDPOINT: http://localhost:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_BUCKET_RAW: cdn-raw
      S3_BUCKET_PROCESSED: cdn-processed
      QUEUE_URL: http://localhost:4566/000000000000/cdn-jobs
    ports:
      - "8787:8787"
    depends_on:
      - postgres
      - minio
      - localstack
