apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-config
  namespace: cdn
data:
  NODE_ENV: "production"
  API_PORT: "3000"

  DB_HOST: "${{ DB_HOST }}"
  DB_PORT: "5432"
  DB_NAME: "cdn_db"

  AWS_REGION: "ap-southeast-2"
  S3_BUCKET_RAW: "${{ S3_BUCKET_RAW }}"
  S3_BUCKET_PROCESSED: "${{ S3_BUCKET_PROCESSED }}"

  CDN_BASE_URL: "https://cdn.easy-cdn.com"

  QUEUE_URL: "${{ QUEUE_URL }}"

  SQS_REGION: "ap-southeast-2"

  ENABLE_CLOUDFRONT_INVALIDATION: "true"
  PURGE_BATCH_SIZE: "10"
  PERMANENT_DELETE_AFTER_DAYS: "30"
