apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdn-api-ingress
  namespace: cdn
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:791954933241:certificate/b55c0599-fbb0-4ca8-930c-15e89960e376
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
    - host: api.easy-cdn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cdn-api-service
                port:
                  number: 3000
