apiVersion: v1
kind: Secret
metadata:
  name: cdn-secrets
  namespace: cdn
type: Opaque
stringData:
  DB_USER: "${{ DB_USER }}"
  DB_PASSWORD: "${{ DB_PASSWORD }}"

  JWT_SECRETE: "${{ JWT_SECRETE }}"

  CLOUDFRONT_DISTRIBUTION_ID: "${{ CLOUDFRONT_DISTRIBUTION_ID }}"
