apiVersion: v1
kind: Secret
metadata:
  name: cdn-secrets
  namespace: cdn
type: Opaque
stringData:
  DB_USER: "cdn"
  DB_PASSWORD: "PASSWORD" # TODO: Replace with actual password

  JWT_SECRETE: "SECRET" # TODO: Replace with actual secret

  S3_ACCESS_KEY_ID: "ID" # TODO: Replace with actual access key id
  S3_SECRET_ACCESS_KEY: "KEY" # TODO: Replace with actual secret access key

  CLOUDFRONT_DISTRIBUTION_ID: "ID" # TODO: Replace with actual distribution id
