version: "3.9"

services:
  cdn-api:
    build:
      context: ../apps/cdn-api
      dockerfile: Dockerfile
    image: ${ECR_API_URL}:${IMAGE_TAG}

  cdn-worker:
    build:
      context: ../apps/cdn-worker
      dockerfile: Dockerfile
    image: ${ECR_WORKER_URL}:${IMAGE_TAG}

